[ApiHttp]
Addr = "0.0.0.0"
Port = 8081

[WsServer]
Addr = "0.0.0.0"
Port = 8082

[IMService]
# IM 服务的地址
Service = "13.228.240.187:8082"
Addr = "0.0.0.0"
Port = 8081

[MySql]
Host = "172.31.21.3"
Port = 3306
Username = "root"
Password = "abcd@1234"
Db = "go_im_test"
Charset = "utf8mb4"

[Redis]
Host = "172.31.21.3"
Port = 6379
Password = ""
Db = 9